# Generated by Django 6.0 on 2026-01-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollenData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('date', models.DateField(verbose_name='Дата')),
                ('hour', models.IntegerField(blank=True, help_text='Час измерения (0-23), если есть', null=True, verbose_name='Час')),
                ('concentration', models.FloatField(help_text='Концентрация пыльцы в grains на кубический метр', verbose_name='Концентрация (grains/m³)')),
            ],
            options={
                'verbose_name': 'Данные о пыльце',
                'verbose_name_plural': 'Данные о пыльце',
                'ordering': ['-date', '-hour'],
            },
        ),
        migrations.CreateModel(
            name='PollenType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('openmeteo_code', models.CharField(help_text='Например: birch_pollen, grass_pollen', max_length=50, unique=True, verbose_name='Код в Open-Meteo')),
                ('category', models.CharField(choices=[('tree', 'Дерево'), ('grass', 'Трава'), ('weed', 'Сорняк')], max_length=10, verbose_name='Категория')),
                ('allergenicity', models.FloatField(choices=[(0.2, 'Очень низкая'), (0.4, 'Низкая'), (0.7, 'Средняя'), (1.0, 'Высокая'), (1.3, 'Очень высокая')], default=0.7, help_text='1.0 = береза (эталон)', verbose_name='Коэффициент аллергенности')),
                ('color', models.CharField(default='#FF0000', max_length=7, verbose_name='Цвет на графике')),
            ],
            options={
                'verbose_name': 'Тип пыльцы',
                'verbose_name_plural': 'Типы пыльцы',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('prevention', 'Профилактика'), ('medication', 'Лекарства'), ('lifestyle', 'Образ жизни'), ('home', 'Дом'), ('outdoor', 'На улице'), ('emergency', 'Экстренные случаи')], default='lifestyle', max_length=20, verbose_name='Категория')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст рекомендации')),
                ('pollen_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pollentype', verbose_name='Тип пыльцы')),
            ],
            options={
                'verbose_name': 'Рекомендация',
                'verbose_name_plural': 'Рекомендации',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensitivity', models.IntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Чувствительность')),
                ('pollen_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergic_users', to='app.pollentype', verbose_name='Тип пыльцы')),
            ],
            options={
                'verbose_name': 'Аллергия пользователя',
                'verbose_name_plural': 'Аллергии пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='profiles', through='app.UserAllergy', to='app.pollentype', verbose_name='Аллергены пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.DeleteModel(
            name='PollenLevel',
        ),
        migrations.AddField(
            model_name='pollendata',
            name='pollen_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='app.pollentype', verbose_name='Тип пыльцы'),
        ),
        migrations.AddField(
            model_name='userallergy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='app.userprofile', verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='pollendata',
            index=models.Index(fields=['date', 'pollen_type'], name='app_pollend_date_a01cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='pollendata',
            index=models.Index(fields=['city'], name='app_pollend_city_00daeb_idx'),
        ),
        migrations.AddIndex(
            model_name='pollendata',
            index=models.Index(fields=['latitude', 'longitude'], name='app_pollend_latitud_ab575f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userallergy',
            unique_together={('user', 'pollen_type')},
        ),
    ]
